terraform {
  required_version = ">= 1.5"

  required_providers {
    # AzureRM 5.6.0 moved Service Bus to control-plane API 2026-01-01. The
    # previous 5.4.x line used API 2024-01-01 and produced a failed Basic
    # namespace whose server-populated properties no longer matched a retry's
    # create payload. 5.7.x contains that Service Bus API upgrade and is the
    # consumer-owned patch line for this root.
    #
    # Do not add zone_redundant or move the demo to Premium: Service Bus now
    # enables zone redundancy automatically for every tier in supported regions.
    # The module's intended Basic SKU, TLS 1.2, and disabled local auth remain.
    #
    # The reusable runner module still declares the broad floor >= 4.63. Root and
    # child constraints intersect, so this tighter root constraint is what selects
    # the compatible provider until a new module release raises its documented
    # minimum to >= 5.6.0.
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 5.7.0"
    }
  }

  # Backend values are injected at runtime via backend.hcl
  # (generated by the deploy workflow from GitHub variables).
  backend "azurerm" {}
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
}
